/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pc_kiviat_radar_chart;

import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import pc_kiviat_radar_chart.kiviatcomponent.KiviatComponent;
import pc_kiviat_radar_chart.models.MyTableModel;

/**
 *
 * @author rooty
 */
public class Main extends javax.swing.JFrame {

    /**
     * 
     */
    private final DefaultTableModel model = new MyTableModel();
    
    private KiviatComponent jPanelKiviat;
    
    
    /**
     * Creates new form Main
     */
    public Main() {
      initComponents();
      myInit();
    }
    
    private void myInit() {
        jTableKiviat.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            jButtonRemoveRow.setEnabled(true);
        });
        
        // Setting the table
        jTableKiviat.setModel(model);
        jTableKiviat.getTableHeader().setReorderingAllowed(false);
        
        // Setting the Kiviat
        jPanelKiviat = new KiviatComponent();
        jPanelKiviat.setModel(model);
        jPanelKiviat.setBounds(0,0,500,500);
        this.add(jPanelKiviat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kiviatComponent2 = new pc_kiviat_radar_chart.kiviatcomponent.KiviatComponent();
        jLabelKiviat = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKiviat = new javax.swing.JTable();
        jButtonAddRow = new javax.swing.JButton();
        jButtonRemoveRow = new javax.swing.JButton();
        kiviatComponent1 = new pc_kiviat_radar_chart.kiviatcomponent.KiviatComponent();

        javax.swing.GroupLayout kiviatComponent2Layout = new javax.swing.GroupLayout(kiviatComponent2);
        kiviatComponent2.setLayout(kiviatComponent2Layout);
        kiviatComponent2Layout.setHorizontalGroup(
            kiviatComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        kiviatComponent2Layout.setVerticalGroup(
            kiviatComponent2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelKiviat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelKiviat.setText("The Great Kiviat !");

        jTableKiviat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name ", "Value", "Vmin", "Vmax"
            }
        ));
        jScrollPane1.setViewportView(jTableKiviat);

        jButtonAddRow.setText("Add a row");
        jButtonAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRowActionPerformed(evt);
            }
        });

        jButtonRemoveRow.setText("Remove row");
        jButtonRemoveRow.setEnabled(false);
        jButtonRemoveRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kiviatComponent1Layout = new javax.swing.GroupLayout(kiviatComponent1);
        kiviatComponent1.setLayout(kiviatComponent1Layout);
        kiviatComponent1Layout.setHorizontalGroup(
            kiviatComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        kiviatComponent1Layout.setVerticalGroup(
            kiviatComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kiviatComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKiviat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddRow, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoveRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKiviat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonRemoveRow, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                            .addComponent(jButtonAddRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(kiviatComponent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRowActionPerformed
        Object[] defaultRow = new Object[]{"Default", 5, 0, 10};
        
        this.model.addRow(defaultRow);
    }//GEN-LAST:event_jButtonAddRowActionPerformed

    private void jButtonRemoveRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveRowActionPerformed
        this.model.removeRow(jTableKiviat.getSelectedRow());
        jButtonRemoveRow.setEnabled(false);
    }//GEN-LAST:event_jButtonRemoveRowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddRow;
    private javax.swing.JButton jButtonRemoveRow;
    private javax.swing.JLabel jLabelKiviat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKiviat;
    private pc_kiviat_radar_chart.kiviatcomponent.KiviatComponent kiviatComponent1;
    private pc_kiviat_radar_chart.kiviatcomponent.KiviatComponent kiviatComponent2;
    // End of variables declaration//GEN-END:variables
}
